name: B

on:
  push:
    branches: [ "master" ]
  repository_dispatch:
    types: 
      - run-action-d
      - run-action-z

jobs:
  action-d:
    runs-on: windows-latest
    steps:
      - name: Set default Variable
        run: |
          Set-Variable -Name "ENV_VAR" -Value "Default"
      - name: Set Variable
        run: |
          if ($env:github_event_name -eq "repository_dispatch") {
            if ($env:github_event_action -eq "run-action-d") {
              Set-Variable -Name "ENV_VAR" -Value "D"
            }
            elseif ($env:github_event_action -eq "run-action-z") {
              Set-Variable -Name "ENV_VAR" -Value "Z"
            }
          }
      - name: Use Environment Variable
        run: echo $ENV_VAR
