
name: B

on:
  push:
    branches: [ "master" ]
  repository_dispatch:
    types: 
      - run-action-d
      - run-action-z
jobs:
  action-d:
    runs-on: windows-latest
    steps:
      - name: Set Variable
        run: |
          echo "ENV_VAR=defaul" >> $GITHUB_ENV
          if [ "$env:TYPE" -eq "run-action-d" ] {
              echo "ENV_VAR=value1" >> $GITHUB_ENV
            }
            elseif [ "$env:TYPE" -eq "type2" ] {
              echo "ENV_VAR=value2" >> $GITHUB_ENV
            }
      - name: Use Environment Variable
        run: echo %ENV_VAR%

