
name: B

on:
  repository_dispatch:
    types: [run-action-d]
jobs:
  action-d:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: |
          if [ "${{ github.event.client_payload.type }}" == "run-action-d" ]; then
            echo "ENV_VAR = D" >> $GITHUB_ENV
          fi
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps for Action D
      - name: Run Action B
        run: echo "Action B is running"
      - name: Use Environment Variable
        run: echo $ENV_VAR

