
name: B

on:
  repository_dispatch:
    types: [run-action-d]

jobs:
  action-d:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps for Action D
      - name: Run Action B
        run: echo "Action B is running"
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: myArtifact
      - name: Read Variable from Artifact
        run: |
          variableValue=$(cat path/to/myArtifact/myVariable.txt)
          echo "The variable value is $variableValue"

