
name: B

on:
  repository_dispatch:
    types: [run-action-d]

jobs:
  action-d:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps for Action D
      - name: Run Action D
        run: echo "Action D is running"
   
