
name: B

on:
  repository_dispatch:
    types: [run-action-d]
env:
  TEST_URL: "default url"
jobs:
  action-d:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: |
          if [ "${{ github.event.client_payload.value1 }}" = "Stage" ]; then
            echo "Setting myVariable to value 1"
            echo "##[set-output name=TEST_URL]value Stageing url here"
          fi
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps for Action D
      - name: Run Action B
        run: echo "Action B is running"
      - name: Display Payload Data
        run: |
          echo $TEST_URL

