

name: C

on:
  workflow_run:
    workflows:
      - A
    types:
      - completed

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: LapusteAlexandru/HomeDemo # Replace with the repository you want to trigger from


    
